trainer_type: XLAClassTrainer

lr: 0.003

bs: 4096
mini_bs: 256

beta1: 0.9
beta2: 0.999
eps: 0.00000001
weight_decay: 0.3

num_epochs: 300
lr_steps: 93900 # 1281167 samples -> 313 steps per epoch
warmup_steps: 10000

checkpoint_first: 10
checkpoint_interval: 25
